"""empty message

Revision ID: 7dfae1faa167
Revises: f73cf39c20d4
Create Date: 2024-05-09 17:35:08.020790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfae1faa167'
down_revision = 'f73cf39c20d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_Person', sa.Integer(), nullable=True),
    sa.Column('favorite_Planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_Person'], ['people.id'], ),
    sa.ForeignKeyConstraint(['favorite_Planet'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
